#!/bin/bash

set -x

DEST="${$HOME}/docker"

mkdir -p ${DEST}
cd ${DEST}

export HOST_NAME="${1:-localhost}"
export APP_RUNTIME="${3:-dotnet}"
export PCS_AUTH_AAD_GLOBAL_TENANTID="$5"
export PCS_AUTH_AAD_GLOBAL_CLIENTID="$6"
export PCS_AUTH_AAD_GLOBAL_LOGINURI="$7"
export PCS_IOTHUB_CONNSTRING="$8"
export PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING="$9"
export PCS_DEVICETELEMETRY_DOCUMENTDB_CONNSTRING="$9"
export PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING="$9"
export PCS_IOTHUBREACT_ACCESS_CONNSTRING="$9"
export PCS_IOTHUBREACT_HUB_NAME="${10}"
export PCS_IOTHUBREACT_HUB_ENDPOINT="${11}"
export PCS_IOTHUBREACT_HUB_PARTITIONS="${12}"
export PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT="${13}"
export PCS_IOTHUBREACT_AZUREBLOB_KEY="${14}"

COMPOSEFILE="https://raw.githubusercontent.com/Azure/azure-iot-pcs-tools/master/remote-monitoring/docker-compose.${APP_RUNTIME}.yml"

wget $COMPOSEFILE -O ${DEST}/docker-compose.yml

> ${DEST}/.env
echo "HOST_NAME=${HOST_NAME}"     >> .env
echo "APP_RUNTIME=${APP_RUNTIME}" >> .env
echo "PCS_AUTH_AAD_GLOBAL_TENANTID=${PCS_AUTH_AAD_GLOBAL_TENANTID}" >> .env
echo "PCS_AUTH_AAD_GLOBAL_CLIENTID=${PCS_AUTH_AAD_GLOBAL_CLIENTID}" >> .env
echo "PCS_AUTH_AAD_GLOBAL_LOGINURI=${PCS_AUTH_AAD_GLOBAL_LOGINURI}" >> .env
echo "PCS_IOTHUB_CONNSTRING=${PCS_IOTHUB_CONNSTRING}"               >> .env
echo "PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING=${PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING}"   >> .env
echo "PCS_DEVICETELEMETRY_DOCUMENTDB_CONNSTRING=${PCS_DEVICETELEMETRY_DOCUMENTDB_CONNSTRING}" >> .env
echo "PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING=${PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING}" >> .env
echo "PCS_IOTHUBREACT_ACCESS_CONNSTRING=${PCS_IOTHUBREACT_ACCESS_CONNSTRING}" >> .env
echo "PCS_IOTHUBREACT_HUB_NAME=${PCS_IOTHUBREACT_HUB_NAME}"                   >> .env
echo "PCS_IOTHUBREACT_HUB_ENDPOINT=${PCS_IOTHUBREACT_HUB_ENDPOINT}"           >> .env
echo "PCS_IOTHUBREACT_HUB_PARTITIONS=${PCS_IOTHUBREACT_HUB_PARTITIONS}"       >> .env
echo "PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT=${PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT}" >> .env
echo "PCS_IOTHUBREACT_AZUREBLOB_KEY=${PCS_IOTHUBREACT_AZUREBLOB_KEY}"         >> .env

> ${DEST}/run.sh
echo "cd ${DEST}"        >> ${DEST}/run.sh
echo "docker-compose up" >> ${DEST}/run.sh
chmod 750 ${DEST}/run.sh

${DEST}/run.sh
